server:
  port: 8085
version: 1.0
spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: qadr_mongodb
      port: 27017
      host: mongodb
  #      uri: mongodb://localhost:27017/qadr
  application:
    environment: production
    config:
      type: git
    name: customer
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF
