spring:
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1
  application:
    environment: production
    config:
      type: git
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
#  logging.level.com.netflix.eureka=OFF
#  logging.level.com.netflix.discovery=OFF
